# Generated by Django 5.2.15 on 2026-06-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchevent',
            new_name='analytics_s_searche_ded083_idx',
            old_name='analytics_s_searched_idx',
        ),
        migrations.RenameIndex(
            model_name='watchevent',
            new_name='analytics_w_watched_0fd4b8_idx',
            old_name='analytics_w_watched_idx',
        ),
        migrations.RenameIndex(
            model_name='watchevent',
            new_name='analytics_w_anime_s_89ffc8_idx',
            old_name='analytics_w_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='watchevent',
            new_name='analytics_w_user_id_bcd327_idx',
            old_name='analytics_w_user_idx',
        ),
    ]
