# Generated by Django 4.2.28 on 2026-03-28 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ananimeclip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('adventure', 'Adventure'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('isekai', 'Isekai'), ('slice of life', 'Slice of Life')], max_length=50)),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('thumbnail', models.ImageField(upload_to='anime/thumbnails/')),
                ('banner', models.ImageField(upload_to='anime/banners/')),
                ('video_url', models.URLField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
