# Generated by Django 4.2.28 on 2026-04-04 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ananimeclip', '0004_anime_age_rating_anime_is_popular_anime_release_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('type', models.CharField(choices=[('thumbnail', 'Thumbnail'), ('banner', 'Banner'), ('logo', 'Logo'), ('poster', 'Poster'), ('card', 'Card Image'), ('background', 'Background')], max_length=20)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_images', to='ananimeclip.anime')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_images', to='ananimeclip.movie')),
            ],
        ),
    ]
