# Generated by Django 4.2.28 on 2026-04-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ananimeclip', '0005_remove_anime_banner_remove_anime_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
