# Generated by Django 4.2.28 on 2026-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ananimeclip', '0006_episode_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='release_day',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='release_time',
        ),
        migrations.AddField(
            model_name='episode',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='release_day',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
        migrations.AddField(
            model_name='episode',
            name='release_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='release_day',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
        migrations.AddField(
            model_name='season',
            name='release_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
