# Generated by Django 4.2.28 on 2026-04-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ananimeclip', '0007_remove_anime_release_date_remove_anime_release_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='status',
        ),
        migrations.AddField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='ongoing', max_length=20),
        ),
    ]
