# Generated by Django 4.2.28 on 2026-04-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ananimeclip', '0008_remove_anime_status_season_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesource',
            name='url',
        ),
        migrations.RemoveField(
            model_name='videosource',
            name='url',
        ),
        migrations.AddField(
            model_name='moviesource',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='videosource',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
