# Generated by Django 4.2.28 on 2026-04-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ananimeclip', '0009_remove_moviesource_url_remove_videosource_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesource',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='videosource',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
