# Generated by Django 4.2.28 on 2026-05-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ananimeclip', '0010_moviesource_poster_videosource_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesource',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videosource',
            name='video',
        ),
        migrations.AddField(
            model_name='moviesource',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videosource',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
