# Generated by Django 4.2.30 on 2026-06-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananimeclip", "0019_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
