# Generated by Django 4.2.30 on 2026-06-25 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ananimeclip", "0020_profile_email_verified_profile_verification_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "avatar",
                    models.CharField(
                        choices=[
                            ("avatar1", "Blue Dragon"),
                            ("avatar2", "Red Fox"),
                            ("avatar3", "Green Wolf"),
                            ("avatar4", "Purple Cat"),
                            ("avatar5", "Gold Eagle"),
                            ("avatar6", "Silver Bear"),
                        ],
                        default="avatar1",
                        max_length=20,
                    ),
                ),
                (
                    "kids_mode",
                    models.BooleanField(
                        default=False, help_text="Restricts content to PG / PG-13 only"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subprofiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
