# Generated by Django 4.2.30 on 2026-06-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ananimeclip", "0021_subprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subprofile",
            old_name="avatars",
            new_name="avatar",
        ),
    ]
