# Generated by Django 4.2.30 on 2026-06-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ananimeclip', '0022_rename_avatars_subprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(
                choices=[('pg', 'PG'), ('pg13', 'PG-13'), ('r', '18+')], default='pg13', max_length=10
            ),
        ),
    ]
