# Generated by Django 4.2.30 on 2026-06-26 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ananimeclip', '0023_movie_age_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='follow',
            name='movie',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='followers',
                to='ananimeclip.movie',
            ),
        ),
        migrations.AlterField(
            model_name='follow',
            name='anime',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='followers',
                to='ananimeclip.anime',
            ),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'anime'), name='unique_follow_user_anime'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_follow_user_movie'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('anime__isnull', False), ('movie__isnull', True)),
                    models.Q(('anime__isnull', True), ('movie__isnull', False)),
                    _connector='OR',
                ),
                name='follow_exactly_one_of_anime_or_movie',
            ),
        ),
    ]
