# Generated by Django 4.2.30 on 2026-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ananimeclip', '0024_alter_follow_unique_together_follow_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_notified',
            field=models.BooleanField(
                default=False,
                help_text='Set once followers have been notified that this movie is out. Used by the notify_movie_releases command to avoid duplicate notifications.',
            ),
        ),
    ]
