# Generated by Django 4.2.30 on 2026-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ananimeclip', '0025_movie_release_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
