# Generated by Django 4.2.30 on 2026-06-27 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ananimeclip', '0028_remove_anime_anime_is_featured_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text="BCP-47 code, e.g. 'en', 'es', 'ja'", max_length=10)),
                ('label', models.CharField(help_text="Shown in the player's CC menu, e.g. 'English'", max_length=50)),
                ('file_url', models.URLField(help_text='URL of a .vtt (WebVTT) file', max_length=500)),
                ('is_default', models.BooleanField(default=False)),
                (
                    'movie_source',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subtitles',
                        to='ananimeclip.moviesource',
                    ),
                ),
                (
                    'video_source',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subtitles',
                        to='ananimeclip.videosource',
                    ),
                ),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddConstraint(
            model_name='subtitle',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('movie_source__isnull', True), ('video_source__isnull', False)),
                    models.Q(('movie_source__isnull', False), ('video_source__isnull', True)),
                    _connector='OR',
                ),
                name='subtitle_exactly_one_of_video_or_movie_source',
            ),
        ),
    ]
